export default {
  description: [
    'The MediaStream Recording API makes it possible to capture the data (audio & video) generated by a MediaStream or HTMLMediaElement object for analysis, processing or saving to disk.'
  ]
}
